### ISSUE TITLE
Compatibility with Posts merging extension

### ISSUE THREAD

**Issue by Galixte** [gn36/phpbb-ext-firstpostedit#5]
Hi @gn36,

i think your extension is not fully compatible with the Posts merging extension: https://github.com/rxu/posts_merging.

If the permissions are set like this:
- Can edit first post of own topics => ON,
- Can edit own replies => ON,
- Can bypass max edit time in first post of own topics => OFF
- Can bypass max edit time for own replies => OFF.

And the setting: “Limit editing time:” is set on 1mn.

When i post a reply named A, after more 1mn i can post a new message B in the previous message A (with “Post merging” functionnality).

I think, maybe your extension should stop the “Post merging” functionnality in this case.

**Comment by gn36** [comment]
I am not sure if I understand your problem correctly, but I also don't really know how the post merging extension works. How does rxu's extension add this merging functionality? Do you post a new reply and then the extension allows you to push the text into the previous post? Or is that an option during the posting of a reply?

This should be a change in the post merging extension, really, since that seems to be ignoring the limit edit time setting. 

Or does it deny editing, if my extension is not installed? The settings you listed are identical to the default settings when editing is allowed, so rxu's extension should permit or deny the same things it permits or denies without firstpostedit installed. So please disable firstpostedit and see if it still does the same. If so, this is a bug in rxu's extension, or you are not using it correctly. Else, I probably need an event in rxu's extension to be able to fix this. The only one he has in there is too late in the process to abort the merge.

From the source code it seems, rxu is using a different time limit for merging called "merge_interval". So maybe you set the wrong time limit.

**Comment by Galixte** [comment]
- I have set the default phpBB option: “Limit editing time:”  on 1mn.
- I have set the next option of“Posts merging” extension on 1 hour (i’t’s the minimum possible): `Posts merging interval - If a user submit more than 2 posts in this time period, posts will be merged into one post. Information about the time passed from the previous post submitting will be added (for each post). Leave blank or set 0 to disable posts merging.`.

On a topic, i post a reply, after 1 mn i can’t edit this reply, but i can merge this reply with a new reply because the “Posts merging” extension allows me to merge during 1 hour after that the last reply posted (if it’s mine).

That’s this case which i point to you.

Otherwise, it’s true there is an option on quick reply and posting.php page (full text editor page): “Do not merge with previous post”. But it’s not a problem, it’s to disable the “Post merging” functionnality when i don’t want to use this functionnality.

Thanks for informations, i will report this issue to @rxu.

**Comment by gn36** [comment]
So that actually sounds completely correct to me, to be honest. The posts merging extension merges all posts that are made within one hour, but you only permit editing for one minute. So after one minute, one cannot edit, but replies get inserted into the previous post. If you want to disable merging, you should probably request to have the minimum changed to an arbitrary value in seconds, so you can also set the merge interval to 1 minute.

It does not seem that rxu made his extension depending on the edit permission, so I think the two extensions do not interact at all.

**Comment by Galixte** [comment]
Ok, thanks. ;)
